# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	addr2line@0.24.2
	adler2@2.0.0
	aho-corasick@1.1.3
	anstream@0.6.18
	anstyle-parse@0.2.6
	anstyle-query@1.1.2
	anstyle-wincon@3.0.7
	anstyle@1.0.10
	anyhow@1.0.98
	autocfg@1.4.0
	backtrace@0.3.74
	bitflags@2.9.0
	bytes@1.10.1
	cfg-if@1.0.0
	cfg_aliases@0.2.1
	clap@4.5.37
	clap_builder@4.5.37
	clap_complete@4.5.47
	clap_lex@0.7.4
	colorchoice@1.0.3
	dbus-crossroads@0.5.2
	dbus-tokio@0.7.6
	dbus@0.9.7
	equivalent@1.0.2
	futures-channel@0.3.31
	futures-core@0.3.31
	futures-executor@0.3.31
	futures-io@0.3.31
	futures-macro@0.3.31
	futures-sink@0.3.31
	futures-task@0.3.31
	futures-util@0.3.31
	futures@0.3.31
	gimli@0.31.1
	hashbrown@0.15.2
	indexmap@2.9.0
	is_terminal_polyfill@1.70.1
	lazy_static@1.5.0
	libc@0.2.172
	libdbus-sys@0.2.5
	log@0.4.27
	matchers@0.1.0
	memchr@2.7.4
	miniz_oxide@0.8.8
	mio@1.0.3
	nix@0.29.0
	nu-ansi-term@0.46.0
	object@0.36.7
	once_cell@1.21.3
	overload@0.1.1
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	pkg-config@0.3.32
	proc-macro2@1.0.95
	quote@1.0.40
	regex-automata@0.1.10
	regex-automata@0.4.9
	regex-syntax@0.6.29
	regex-syntax@0.8.5
	regex@1.11.1
	rustc-demangle@0.1.24
	serde@1.0.219
	serde_derive@1.0.219
	serde_ignored@0.1.11
	serde_spanned@0.6.8
	sharded-slab@0.1.7
	signal-hook-registry@1.4.4
	slab@0.4.9
	smallvec@1.15.0
	socket2@0.5.9
	strsim@0.11.1
	syn@2.0.100
	thiserror-impl@2.0.12
	thiserror@2.0.12
	thread_local@1.1.8
	tokio-macros@2.5.0
	tokio@1.44.2
	toml@0.8.20
	toml_datetime@0.6.8
	toml_edit@0.22.24
	tracing-attributes@0.1.28
	tracing-core@0.1.33
	tracing-log@0.2.0
	tracing-subscriber@0.3.19
	tracing@0.1.41
	unicode-ident@1.0.18
	utf8parse@0.2.2
	valuable@0.1.1
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	winnow@0.7.6
"

declare -A GIT_CRATES=(
	[sdtx-tokio]='https://github.com/linux-surface/libsurfacedtx;940c9a0cade870218ef8fee5f16df1eef8853c44;libsurfacedtx-%commit%/sdtx-tokio'
	[sdtx]='https://github.com/linux-surface/libsurfacedtx;940c9a0cade870218ef8fee5f16df1eef8853c44;libsurfacedtx-%commit%/sdtx'
)

inherit cargo systemd udev

DESCRIPTION="Surface Detachment System (DTX) Daemon"
HOMEPAGE="https://github.com/linux-surface/surface-dtx-daemon"
SRC_URI="
	https://github.com/linux-surface/${PN}/archive/refs/tags/v${PV}-1.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/${P}-1"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

src_install() {
	pushd ${PN} 2>/dev/null || die
	cargo_src_install
	popd 2>/dev/null || die

	udev_dorules etc/udev/40-surface_dtx.rules
	systemd_dounit etc/systemd/surface-dtx-daemon.service

	insinto /etc/dbs-1/system.d
	doins etc/dbus/org.surface.dtx.conf

	chmod +x etc/dtx/attach.sh || die
	chmod +x etc/dtx/detach.sh || die

	insinto /etc/surface-dtx
	doins etc/dtx/surface-dtx-daemon.conf
	doins etc/dtx/attach.sh
	doins etc/dtx/detach.sh

}

pkg_postinst() {
	udev_reload
}

pkg_postrm() {
	udev_reload
}
