# Copyright 2025-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	aho-corasick@1.1.4
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.13
	anyhow@1.0.100
	bitflags@2.10.0
	bytes@1.11.0
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	clap@4.5.53
	clap_builder@4.5.53
	clap_complete@4.5.63
	clap_lex@0.7.6
	colorchoice@1.0.4
	dbus-crossroads@0.5.3
	dbus-tokio@0.7.6
	dbus@0.9.10
	equivalent@1.0.2
	errno@0.3.14
	futures-channel@0.3.31
	futures-core@0.3.31
	futures-executor@0.3.31
	futures-io@0.3.31
	futures-macro@0.3.31
	futures-sink@0.3.31
	futures-task@0.3.31
	futures-util@0.3.31
	futures@0.3.31
	hashbrown@0.16.1
	indexmap@2.12.1
	is_terminal_polyfill@1.70.2
	lazy_static@1.5.0
	libc@0.2.178
	libdbus-sys@0.2.7
	log@0.4.29
	matchers@0.2.0
	memchr@2.7.6
	mio@1.1.1
	nix@0.30.1
	nu-ansi-term@0.50.3
	once_cell@1.21.3
	once_cell_polyfill@1.70.2
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	pkg-config@0.3.32
	proc-macro2@1.0.104
	quote@1.0.42
	regex-automata@0.4.13
	regex-syntax@0.8.8
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_ignored@0.1.14
	serde_spanned@1.0.4
	sharded-slab@0.1.7
	signal-hook-registry@1.4.8
	slab@0.4.11
	smallvec@1.15.1
	socket2@0.6.1
	strsim@0.11.1
	syn@2.0.111
	thiserror-impl@2.0.17
	thiserror@2.0.17
	thread_local@1.1.9
	tokio-macros@2.6.0
	tokio@1.48.0
	toml@0.9.10+spec-1.1.0
	toml_datetime@0.7.5+spec-1.1.0
	toml_parser@1.0.6+spec-1.1.0
	toml_writer@1.0.6+spec-1.1.0
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-log@0.2.0
	tracing-subscriber@0.3.22
	tracing@0.1.44
	unicode-ident@1.0.22
	utf8parse@0.2.2
	valuable@0.1.1
	wasi@0.11.1+wasi-snapshot-preview1
	windows-link@0.2.1
	windows-sys@0.59.0
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows-targets@0.53.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@0.7.14
"

declare -A GIT_CRATES=(
	[sdtx-tokio]='https://github.com/linux-surface/libsurfacedtx;c18b581ede967fb59769e6fec49aca8676ba6077;libsurfacedtx-%commit%/sdtx-tokio'
	[sdtx]='https://github.com/linux-surface/libsurfacedtx;c18b581ede967fb59769e6fec49aca8676ba6077;libsurfacedtx-%commit%/sdtx'
)

inherit cargo systemd udev

DESCRIPTION="Surface Detachment System (DTX) Daemon"
HOMEPAGE="https://github.com/linux-surface/surface-dtx-daemon"
SRC_URI="
	https://github.com/linux-surface/${PN}/archive/refs/tags/v${PV}-1.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/${P}-1"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

src_install() {
	pushd ${PN} 2>/dev/null || die
	cargo_src_install
	popd 2>/dev/null || die

	udev_dorules etc/udev/40-surface_dtx.rules
	systemd_dounit etc/systemd/surface-dtx-daemon.service

	insinto /etc/dbus-1/system.d
	doins etc/dbus/org.surface.dtx.conf

	chmod +x etc/dtx/attach.sh || die
	chmod +x etc/dtx/detach.sh || die

	insinto /etc/surface-dtx
	doins etc/dtx/surface-dtx-daemon.conf
	doins etc/dtx/attach.sh
	doins etc/dtx/detach.sh

}

pkg_postinst() {
	udev_reload
}

pkg_postrm() {
	udev_reload
}
