# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4

EAPI=8

CRATES="
	addr2line-0.21.0
	adler-1.0.2
	aho-corasick-1.1.2
	anstream-0.6.13
	anstyle-1.0.6
	anstyle-parse-0.2.3
	anstyle-query-1.0.2
	anstyle-wincon-3.0.2
	anyhow-1.0.81
	autocfg-1.1.0
	backtrace-0.3.69
	bitflags-2.4.2
	bytes-1.5.0
	cc-1.0.90
	cfg-if-1.0.0
	cfg_aliases-0.1.1
	clap-4.5.2
	clap_builder-4.5.2
	clap_complete-4.5.1
	clap_lex-0.7.0
	colorchoice-1.0.0
	dbus-0.9.7
	dbus-crossroads-0.5.2
	dbus-tokio-0.7.6
	equivalent-1.0.1
	futures-0.3.30
	futures-channel-0.3.30
	futures-core-0.3.30
	futures-executor-0.3.30
	futures-io-0.3.30
	futures-macro-0.3.30
	futures-sink-0.3.30
	futures-task-0.3.30
	futures-util-0.3.30
	gimli-0.28.1
	hashbrown-0.14.3
	indexmap-2.2.5
	lazy_static-1.4.0
	libc-0.2.153
	libdbus-sys-0.2.5
	log-0.4.21
	matchers-0.1.0
	memchr-2.7.1
	miniz_oxide-0.7.2
	mio-0.8.11
	nix-0.27.1
	nix-0.28.0
	nu-ansi-term-0.46.0
	object-0.32.2
	once_cell-1.19.0
	overload-0.1.1
	pin-project-lite-0.2.13
	pin-utils-0.1.0
	pkg-config-0.3.30
	proc-macro2-1.0.79
	quote-1.0.35
	regex-1.10.3
	regex-automata-0.1.10
	regex-automata-0.4.6
	regex-syntax-0.6.29
	regex-syntax-0.8.2
	rustc-demangle-0.1.23
	serde-1.0.197
	serde_derive-1.0.197
	serde_ignored-0.1.10
	serde_spanned-0.6.5
	sharded-slab-0.1.7
	signal-hook-registry-1.4.1
	slab-0.4.9
	smallvec-1.13.1
	socket2-0.5.6
	strsim-0.11.0
	syn-2.0.52
	thiserror-1.0.58
	thiserror-impl-1.0.58
	thread_local-1.1.8
	tokio-1.36.0
	tokio-macros-2.2.0
	toml-0.8.11
	toml_datetime-0.6.5
	toml_edit-0.22.7
	tracing-0.1.40
	tracing-attributes-0.1.27
	tracing-core-0.1.32
	tracing-log-0.2.0
	tracing-subscriber-0.3.18
	unicode-ident-1.0.12
	utf8parse-0.2.1
	valuable-0.1.0
	wasi-0.11.0+wasi-snapshot-preview1
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-x86_64-pc-windows-gnu-0.4.0
	windows-sys-0.48.0
	windows-sys-0.52.0
	windows-targets-0.48.5
	windows-targets-0.52.4
	windows_aarch64_gnullvm-0.48.5
	windows_aarch64_gnullvm-0.52.4
	windows_aarch64_msvc-0.48.5
	windows_aarch64_msvc-0.52.4
	windows_i686_gnu-0.48.5
	windows_i686_gnu-0.52.4
	windows_i686_msvc-0.48.5
	windows_i686_msvc-0.52.4
	windows_x86_64_gnu-0.48.5
	windows_x86_64_gnu-0.52.4
	windows_x86_64_gnullvm-0.48.5
	windows_x86_64_gnullvm-0.52.4
	windows_x86_64_msvc-0.48.5
	windows_x86_64_msvc-0.52.4
	winnow-0.6.5
"

declare -A GIT_CRATES=(
	[sdtx]="https://github.com/linux-surface/libsurfacedtx;6da7c74d931808c86c515df3425d3112e40a2007;libsurfacedtx-%commit%/sdtx"
	[sdtx-tokio]="https://github.com/linux-surface/libsurfacedtx;6da7c74d931808c86c515df3425d3112e40a2007;libsurfacedtx-%commit%/sdtx-tokio"
)

inherit cargo systemd udev

DESCRIPTION="Surface Detachment System (DTX) Daemon"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/linux-surface/surface-dtx-daemon/"
SRC_URI="
	https://github.com/linux-surface/surface-dtx-daemon/archive/refs/tags/v${PV}-1.tar.gz -> ${PN}.tar.gz
	$(cargo_crate_uris)
"

S="${WORKDIR}/${P}-1"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT Unicode-DFS-2016 Unlicense ZLIB"
SLOT="0"
KEYWORDS="~amd64"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_install() {
	pushd ${PN} 2>/dev/null || die
	cargo_src_install
	popd 2>/dev/null || die

	udev_dorules etc/udev/40-surface_dtx.rules
	systemd_dounit etc/systemd/surface-dtx-daemon.service

	insinto /etc/dbus-1/system.d
	doins etc/dbus/org.surface.dtx.conf

	chmod +x etc/dtx/attach.sh || die
	chmod +x etc/dtx/detach.sh || die

	dodir /etc/surface-dtx
	insinto /etc/surface-dtx
	doins etc/dtx/surface-dtx-daemon.conf
	doins etc/dtx/attach.sh
	doins etc/dtx/detach.sh

}

pkg_postinst() {
	udev_reload
}

pkg_postrm() {
	udev_reload
}
